apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-mounting-secret
  labels:
    app: webserver
spec:
  containers:
  - name: demo-pod
    image: hsienwu830808/docker-demo
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: secret-volumn
      mountPath: /etc/creds
      readOnly: true
  volumes:
  - name: secret-volumn
    secret:
      secretName: demo-secret-from-yaml
