apiVersion: v1
kind: Pod
metadata:
  name: my-second-pod
  labels:
    app: nodejs
    tier: backend
  annotations:
    version: v3.0.0
    release_data: 2020/04/01
    contact: hsienwu830808@gamil.com
spec:
  containers:
  - name: pod-demo
    image: hsienwu830808/docker-demo:v3.0.0
    ports:
    - containerPort: 3000  
  nodeSelector:
    kubernetes.io/hostname: m01
